### ISSUE TITLE
upgrade to broccoli-persistent-filter

### ISSUE THREAD

**Issue by stefanpenner** [sindresorhus/broccoli-autoprefixer#11]
It's much faster the broccoli-filter, we have plans to upstream the work. @joliss is thinkin on how to elegantly incorporate some of the ideas. At which time, we will re-merge the two projects.

Given projects such as: https://gist.github.com/workmanw/fdf85772fb8e61bfbeb8
BPF will easily reduce the 86ms rebuild time to 5-10ms (or better)

If no one beats me to it, later this week I will try to make the update myself.

Some examples doing similar upgrade (maybe i get lucky and someone beats me to it):

* https://github.com/rwjblue/broccoli-string-replace/pull/4/files
* rwjblue/broccoli-jshint@d272e64
* https://github.com/toranb/broccoli-ember-hbs-template-compiler/pull/13/files

**Comment by sindresorhus** [comment]
Good to hear. Added you to the repo and npm package.

See https://github.com/sindresorhus/broccoli-autoprefixer/pull/10 as a start.

It should be implemented same as: https://github.com/sindresorhus/broccoli-defeatureify/pull/2

**Comment by workmanw** [comment]
:D Any chance I could talk you into cutting a new version?

**Comment by stefanpenner** [comment]
We will cut after we have a chance to verify in our app

**Comment by stefanpenner** [comment]
@workmanw 

```
➜  broccoli-autoprefixer git:(master) npm publish
+ broccoli-autoprefixer@4.1.0
```
