### ISSUE TITLE
Update autoprefixer

### ISSUE THREAD

**Issue by erichonkanen** [sindresorhus/broccoli-autoprefixer#14]
hello, can you bump the autoprefixer version to the latest `7.1.4`?

Thanks

https://github.com/sindresorhus/broccoli-autoprefixer/blob/master/package.json#L33

**Comment by kevva** [comment]
`^7.0.0` will install `7.1.4`. You can read more about it here https://nodesource.com/blog/semver-tilde-and-caret/. Unless there's a critical bugfix I don't see the point in bumping it.
