### ISSUE TITLE
Inline source maps are not working

### ISSUE THREAD

**Issue by aexmachina** [sindresorhus/broccoli-autoprefixer#8]
This issue was originally posted [on autoprefixer](https://github.com/postcss/autoprefixer/issues/384#issuecomment-69847140) but @ai instructed me to add it here.

 I'm using broccoli-autoprefixer in an ember-cli project, and the source map is not working when autoprefixer is used. If I remove autoprefixer then the source maps work correctly.

- ember-cli-sass is correctly producing an inline source map `/*# sourceMappingURL=data:application/json;base64,...` 
- I'm setting `sourcemap: true` when I call broccoli-autoprefixer
- There is a `sourceMappingURL` included at the end of the CSS file, but it's broken: DevTools doesn't show the SCSS source, just the final output CSS

FWIW, I'd also like to add that I'd much prefer to be able to use a `.map` file, rather than having to embed the source map inline in the CSS file. The current beta of broccoli-sass (I'm a maintainer of broccoli-sass) uses `sourcesContent` to embed the source files into the source map, so this is quite a bit of data and I'd much prefer for the browser to be able to request the source map when it needs it, rather than it being force-fed inline in the CSS.

I can provide an example repo if this helps to debug the problem.

**Comment by sindresorhus** [comment]
// @jamesreggio

**Comment by sindresorhus** [comment]
I dunno. I've only had problems with [Autoprefixer source map](https://github.com/sindresorhus/gulp-autoprefixer/issues).

There's like almost no code here: https://github.com/sindresorhus/broccoli-autoprefixer/blob/4c0022731782844dc17e37a99566e58d20d18248/index.js#L22-L32

Not sure what I would different.

**Comment by jamesreggio** [comment]
I'd be happy to investigate, but could you please provide an example?

**Comment by aexmachina** [comment]
Okay I've tracked down the problem to the following in our CSS:

- `@import url('...');`
- `content: "⚠";`

Once I remove these it works just fine :) Perhaps this issue should be raised on another module?
